"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Toaster } from "@/components/ui/toaster";
import React, { createContext, useState, useContext, ReactNode } from "react";
import { User } from "firebase/auth";
import { UserProvider, useUserContext } from "@/contexts/userContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   viewport: "width=device-width, initial-scale=1, maximum-scale=1 ",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [user, setUser] = useState<User | null>(null);

  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <main>{children}</main>
          <Toaster />
        </body>
      </UserProvider>
    </html>
  );
}

// export default function Layout({ children }: LayoutProps) {

//   return (
//     <html lang="en">
//       <UserProvider>
//         <body className={inter.className}>
//           <UserContext.Provider value={{ user, setUser }}>
//             <main>{children}</main>
//             <Toaster />
//           </UserContext.Provider>
//         </body>
//       </UserProvider>
//     </html>
//   );
// }
